; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@^6.3.0
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	kosme/arduinoFFT               ; FFT de 1024 pts
    esp32async/AsyncTCP            ; TCP asíncrono (ESP32)
    esp32async/ESPAsyncWebServer   ; HTTP + WebSocket
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit BusIO@^1.14.5    
upload_speed = 460800
monitor_speed = 115200
board_build.filesystem = spiffs

; Configuración para ESP32-S3-WROOM-1-N4R2 (descomentar si usas esta placa, es decir desde la siguiente linea quita el ';' al inicio de cada línea)
; board_build.arduino.memory_type = qio_qspi
; board_build.flash_mode = qio
; board_build.psram_type = qio
; board_upload.flash_size = 4MB
; board_upload.maximum_size = 4194304
; board_build.partitions = default.csv
; board_build.extra_flags = 
;   -DBOARD_HAS_PSRAM
